config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  
  resources :invoices do
    member do
      get 'show_project'
      post 'project_new_or_add'
    end
  end
  
  resources :contacts
  
  resources :events do
    member do
      get 'start'
      get 'stop_now'
      get 'show_project'
    end
  end
  
  resources :projects do
    member do
      get 'stop'
    end
  end
  
  root :to => 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :project
  belongs_to :invoice, optional: true

  validates_presence_of :project_id
  validates_numericality_of :rate
  validates_presence_of :description, :on => 'update'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :stop_now]

  def index
    @events = Event.order("project_id,start_at").paginate(:page => params[:page])
  end

  def show
  end

  def new
    @event = Event.new(:rate => $default_rate)
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to show_project_event_url(@event.project_id), :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    respond_to do |fmt|
      if @event.update(event_params)
        fmt.html {redirect_to show_project_event_url(@event.project_id), :notice  => "Successfully updated event."}
        fmt.json {respond_with_bip(@event)}
      else
        fmt.html {render :action => 'edit'}
        fmt.json {respond_with_bip(@event)}
      end
    end
  end

  def destroy
    @event.destroy
    redirect_to show_project_event_url(@event.project_id), :notice => "Successfully deleted event."
  end

  def start
    @project = Project.find(params[:id])
    @event = Event.create(:project_id => @project.id, :rate => @project.rate, :start_at => Time.now)
    render :action => 'edit'
  end

  def stop_now
    @event.update_attributes(:end_at => Time.now)
#     if @event.save
#       redirect_to show_project_event_url(@event.project_id), :notice => "Event stopped."
#     else
      render :action => 'edit'
#     end
  end

  def show_project
    @p = Project.find params[:id]
    @title = "Activity for #{@p.name}"
    @events = Event.where(['project_id = ?', params[:id]]).order('start_at DESC').paginate(:page => params[:page])
    render :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_at, :end_at, :project_id, :invoice_id, :description, :rate)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :start_at, "Start" %><br />
    <%= f.text_field :start_at %>
  </p>
  <p>
    <%= f.label :end_at, "End" %><br />
    <%= f.text_field :end_at %>
  </p>
  <p>
    <%= f.label :project_id %><br />
    <%= f.select :project_id, Project.order(:name).collect {|p| [p.name, p.id]}%>
  </p>
  <p>
    <%= f.label :rate, "Rate per hour" %><br />
    <%= f.number_field :rate %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description, :size => 60 %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/events/edit.html.erb
<% title "Edit Event" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @event %> |
  <%= link_to "View All", events_path %>
</p>

app/views/events/index.html.erb
<% title @title || "Activity" %>
<% if request.parameters[:action] == 'show_project' %>
  <p><%= link_to "New Activity", start_event_path(@p.id) %></p>
  <%= form_tag("/invoices/#{@p.id}/project_new_or_add") %>
<% else %>
  <p><%= link_to "New Activity", new_event_path %></p>
<% end %>

<%= will_paginate @events %>
<table>
  <tr>
    <th>Sel</th>
    <th>Started</th>
    <th>Ended</th>
<% if request.parameters[:action] != 'show_project' %>
    <th>Project</th>
<% else %>
    <th>Invoice</th>
<% end %>
    <th>Description</th>
    <th></th>
  </tr>
  <% for event in @events %>
    <tr class="<%= cycle('light','dark') %>">
      <td><% unless (event.end_at.nil? or request.parameters[:action] != 'show_project' or !event.invoice_id.nil?) %><%= check_box_tag "select[#{event.id}]", event.id %><% end %></td>
      <td><%= event.start_at.to_s(:medium) %></td>
      <td><%= event.end_at.nil? ? '' : event.end_at.to_s(:medium) %></td>
    <% if request.parameters[:action] != 'show_project' %>
      <td><%= event.project.name %></td>
    <% else %>
      <td><%= event.invoice_id.nil? ? '' : event.invoice_id %></td>
    <% end %>
      <td><%= best_in_place(event, :description) %></td>
      <td>
        <%= link_to "Edit", edit_event_path(event) %> |
        <%= link_to_if event.end_at.nil?, "Stop", stop_now_event_path(event) %> |
        <%= link_to "Del", event, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
  <% if request.parameters[:action] == 'show_project' %>
    <tr>
      <td colspan=6>Memo: <%= text_field_tag 'invoice_memo', '', size: 30 %><%= submit_tag "Generate Invoice" %> | <%= submit_tag "Add to Invoice" %><%= text_field_tag 'invoice_id', '', :size => 4 %></td>
    </tr>
  <% end %>
</form>
</table>

<%= will_paginate @events %>

app/views/events/new.html.erb
<% title "New Event" %>

<%= render 'form' %>

<p><%= link_to "Back to List", events_path %></p>

app/views/events/show.html.erb
<% title "Event" %>

<p>
  <strong>Start Time:</strong>
  <%= @event.start_at %>
</p>
<p>
  <strong>Stop Time:</strong>
  <%= @event.end_at %>
</p>
<p>
  <strong>Project:</strong>
  <%= @event.project.name %>
</p>
<p>
  <strong>Event Detail:</strong>
  <%= @event.description %>
</p>

<p>
  <%= link_to "Edit", edit_event_path(@event) %> |
  <%= link_to "Destroy", @event, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", events_path %>
</p>