config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  
  resources :invoices do
    member do
      get 'show_project'
      post 'project_new_or_add'
    end
  end
  
  resources :contacts
  
  resources :events do
    member do
      get 'start'
      get 'stop_now'
      get 'show_project'
    end
  end
  
  resources :projects do
    member do
      get 'stop'
    end
  end
  
  root :to => 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :events
  belongs_to :contact

  validates_presence_of :contact_id
  validates_presence_of :rate
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.order(:name).paginate(:page => params[:page])
    @open_events = Hash.new
    @projects.each do |p|
      e = Event.where(["project_id = ? and end_at is NULL", p.id]).first
      @open_events[p.id] = e.id unless e.nil?
    end
  end

  def stop
    @project = Project.find(params[:id])
    @event = Event.where(["project_id = ? AND end_at is NULL", @project.id]).first
#     if @event.update_attributes(:end_at => Time.now)
#       redirect_to events_url, :notice => "Event stopped."
#     else
    @event.update_attributes(:end_at => Time.now)
      redirect_to edit_event_path(@event)
#     end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to projects_url, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, :notice => "Successfully destroyed project."
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :contact_id, :rate)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :contact %><br />
    <%= f.select :contact_id, Contact.all.order(:name).collect {|c| [c.name, c.id]} %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description  %>
  </p>
  <p>
    <%= f.label :rate, "Default rate to charge" %><br />
    <%= f.text_field :rate %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/projects/index.html.erb
<% title "Projects" %>
<p><%= link_to "New Project", new_project_path %></p>

<%= will_paginate @projects %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Default Rate</th>
    <th>Contact</th>
  </tr>
  <% for project in @projects %>
    <tr class="<%= cycle('light','dark')%>">
      <td><%= link_to project.name, edit_project_path(project) %></td>
      <td><%= project.description.truncate(50) %></td>
      <td class='align-right'><%= number_to_currency(project.rate) %></td>
      <td><%= link_to project.contact.name, "mailto://#{project.contact.email}" %></td>
      <td><%= link_to "Start", start_event_path(project) %> |
          <%= link_to_unless @open_events[project.id].nil?, "Stop", stop_project_path(project) %> |
          <%= link_to "Activity", show_project_event_path(project) %> |
          <%= link_to "Invoices", show_project_invoice_path(project) %> |
          <%= link_to "Del", project, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @projects %>

app/views/projects/new.html.erb
<% title "New Project" %>

<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/show.html.erb
<% title "Project" %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to "Destroy", @project, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", projects_path %>
</p>